### ISSUE TITLE
 질문 TO 은호형

### ISSUE THREAD

**Issue by kimys1324** [cenenh/sGen_Remind.me#10]
질문 TO 은호형
1. 아까 말했던거 로그인 부분먼저요 형! ㅎㅎ
2. 은호형 Reminder에 add할때 scrap이 아니면 img가 없는데, "img":null 로 넘겨도되나욥!?
3. sign-up using Email 부분에서 response가 404 error로 빨간줄로 나와요 형!
4. 늦게 말씀드려서 죄송해요 형 ㅠㅠ

**Comment by kimys1324** [comment]
- 형 그 List에서도 스위치로 on off해서 알림을 받고싶은 거랑 안받고싶은 거가 나뉘어져있어야 되는데 그게 없는거 같아요!

**Comment by cenenh** [comment]
1. 메일 확인 바람
2. img를 생략해도 가능, null말고 그냥 생략
3. 해당 부분 캡쳐해서 올려줘.
4. 괜찮아 ㅎㅎ
5. 그거 구현 완료되었는데 readme 오늘 밤에 수정할게.

**Comment by cenenh** [comment]
![default](https://cloud.githubusercontent.com/assets/9075767/12205055/a8e28350-b67b-11e5-8e5e-df43eb9578df.PNG)

**Comment by cenenh** [comment]
![default](https://cloud.githubusercontent.com/assets/9075767/12205140/235f2afc-b67c-11e5-8a34-b1218945df0f.PNG)
